// frameworks/nextjs-v14.2.3/app/text-only/page.tsx
import { API_BASE } from '@/lib/config';
import { ReviewCard } from '../components/ReviewCard';
import Link from 'next/link';

export default async function TextOnlyPage({
  searchParams,
}: {
  searchParams: { table?: string; limit?: string; delay?: string };
}) {
  const table = searchParams.table ?? 'hotel_reviews';
  const limit = searchParams.limit ?? '50';
  const delay = searchParams.delay ?? '0';

  const res = await fetch(
    `${API_BASE}/api/reviews?table=${table}&limit=${limit}&delay=${delay}`,
    { cache: 'no-store' }
  );
  const { data: reviews, total } = await res.json();

  return (
    <div>
      <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
        <h1 className="text-2xl font-bold">
          Text Only <span className="text-gray-400 text-base font-normal">({total} total)</span>
        </h1>
        <div className="flex gap-2 text-sm">
          <Link href="?table=hotel_reviews" className={`px-3 py-1 rounded-full border ${table === 'hotel_reviews' ? 'bg-blue-600 text-white border-blue-600' : 'border-gray-300 hover:bg-gray-50'}`}>Table 1</Link>
          <Link href="?table=hotel_reviews_dataset" className={`px-3 py-1 rounded-full border ${table === 'hotel_reviews_dataset' ? 'bg-blue-600 text-white border-blue-600' : 'border-gray-300 hover:bg-gray-50'}`}>Table 2</Link>
        </div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
        {reviews.map((r: any) => <ReviewCard key={r.id} review={r} />)}
      </div>
    </div>
  );
}

// frameworks/nuxt-v3.11.2/pages/text-only.vue
<script setup lang="ts">
const route = useRoute();
const { getReviews } = useApi();
const table = computed(() => (route.query.table as string) || 'hotel_reviews');
const { data, refresh } = await useAsyncData('text-only', () => getReviews({ table: table.value, limit: 50 }), { watch: [table] });
</script>

<template>
  <div>
    <div class="flex items-center justify-between mb-6 flex-wrap gap-3">
      <h1 class="text-2xl font-bold">Text Only <span class="text-gray-400 text-base font-normal">({{ data?.total }} total)</span></h1>
      <div class="flex gap-2 text-sm">
        <NuxtLink :to="{ query: { table: 'hotel_reviews' } }" :class="table === 'hotel_reviews' ? 'px-3 py-1 rounded-full border bg-blue-600 text-white border-blue-600' : 'px-3 py-1 rounded-full border border-gray-300 hover:bg-gray-50'">Table 1</NuxtLink>
        <NuxtLink :to="{ query: { table: 'hotel_reviews_dataset' } }" :class="table === 'hotel_reviews_dataset' ? 'px-3 py-1 rounded-full border bg-blue-600 text-white border-blue-600' : 'px-3 py-1 rounded-full border border-gray-300 hover:bg-gray-50'">Table 2</NuxtLink>
      </div>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
      <ReviewCard v-for="r in data?.data" :key="r.id" :review="r" />
    </div>
  </div>
</template>
