// frameworks/nextjs-v15.1.4/app/components/ReviewCardWithVideo.tsx
import type { Review } from '@/lib/config';
import { API_BASE } from '@/lib/config';

function Stars({ rating }: { rating: number | null }) {
  const r = rating ?? 0;
  return <span className="text-yellow-500 text-xs whitespace-nowrap shrink-0">{'★'.repeat(r)}{'☆'.repeat(5 - r)}</span>;
}
interface VideoMeta { url: string; width: number; height: number; }

export async function ReviewCardWithVideo({ review, resolution }: { review: Review; resolution: string }) {
  const videoMeta: VideoMeta | null = await fetch(`${API_BASE}/api/media/video/${resolution}`, { cache: 'no-store' })
    .then(r => r.json()).catch(() => null);
  return (
    <article className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
      {videoMeta?.url && (
        <video className="w-full" width={videoMeta.width} height={videoMeta.height}>
          <source src={videoMeta.url} type="video/mp4" />
        </video>
      )}
      <div className="p-5">
        <div className="flex items-start justify-between gap-2 mb-2">
          <h3 className="font-semibold text-gray-800 text-sm leading-snug">{review.review_title ?? 'Untitled'}</h3>
          <Stars rating={review.review_rating} />
        </div>
        <p className="text-gray-600 text-sm line-clamp-3 mb-3">{review.review_text ?? '—'}</p>
        <div className="text-xs text-gray-400 flex flex-wrap gap-2">
          <span className="font-medium text-gray-700">{review.name ?? 'Unknown Hotel'}</span>
          {review.city && <span>· {review.city}</span>}
          {review.review_username && <span>by {review.review_username}</span>}
        </div>
      </div>
    </article>
  );
}

// frameworks/nuxt-v4.2.2/app/components/ReviewCardWithVideo.vue
<script setup lang="ts">
import type { Review } from '~/utils/config';
const props = defineProps<{ review: Review; resolution: string }>();
const { getVideo } = useApi();
const { data: video } = await useAsyncData(`video-${props.resolution}`, () => getVideo(props.resolution));
const stars = computed(() => {
  const r = props.review.review_rating ?? 0;
  return '★'.repeat(r) + '☆'.repeat(5 - r);
});
</script>

<template>
  <article class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
    <video v-if="video" class="w-full"
      :width="video.width" :height="video.height">
      <source :src="video.url" type="video/mp4" />
    </video>
    <div class="p-5">
      <div class="flex items-start justify-between gap-2 mb-2">
        <h3 class="font-semibold text-gray-800 text-sm leading-snug">{{ review.review_title || 'Untitled' }}</h3>
        <span class="text-yellow-500 text-xs whitespace-nowrap shrink-0">{{ stars }}</span>
      </div>
      <p class="text-gray-600 text-sm mb-3 line-clamp-3">{{ review.review_text || '—' }}</p>
      <div class="text-xs text-gray-400 flex flex-wrap gap-2">
        <span class="font-medium text-gray-700">{{ review.name || 'Unknown Hotel' }}</span>
        <span v-if="review.city">· {{ review.city }}</span>
      </div>
    </div>
  </article>
</template>
