// frameworks/nextjs-v14.2.3/app/text-videos/[resolution]/page.tsx
import { API_BASE, VALID_RESOLUTIONS, VIDEO_RESOLUTIONS } from '@/lib/config';
import { ReviewCardWithVideo } from '../../components/ReviewCardWithVideo';
import Link from 'next/link';
import { notFound } from 'next/navigation';

export default async function TextVideosPage({
  params,
  searchParams,
}: {
  params: { resolution: string };
  searchParams: { table?: string; limit?: string; delay?: string };
}) {
  const { resolution } = params;
  if (!VIDEO_RESOLUTIONS.includes(resolution)) return notFound();

  const table = searchParams.table ?? 'hotel_reviews';
  const limit = searchParams.limit ?? '12';
  const delay = searchParams.delay ?? '0';

  const res = await fetch(
    `${API_BASE}/api/reviews?table=${table}&limit=${limit}&delay=${delay}`,
    { cache: 'no-store' }
  );
  const { data: reviews, total } = await res.json();

  return (
    <div>
      <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
        <h1 className="text-2xl font-bold">
          Videos <span className="text-blue-600">{resolution}</span>{' '}
          <span className="text-gray-400 text-base font-normal">({total} total)</span>
        </h1>
        <div className="flex gap-2 flex-wrap text-sm">
          {VIDEO_RESOLUTIONS.map(r => (
            <Link key={r} href={`/text-videos/${r}?table=${table}`}
              className={`px-3 py-1 rounded-full border ${resolution === r ? 'bg-blue-600 text-white border-blue-600' : 'border-gray-300 hover:bg-gray-50'}`}>
              {r}
            </Link>
          ))}
        </div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {reviews.map((r: any) => <ReviewCardWithVideo key={r.id} review={r} resolution={resolution} />)}
      </div>
    </div>
  );
}

// frameworks/nuxt-v4.2.2/app/pages/text-videos/[resolution].vue
<script setup lang="ts">
import { VIDEO_RESOLUTIONS } from '~/utils/config';
const route = useRoute();
const resolution = computed(() => route.params.resolution as string);
const table = computed(() => (route.query.table as string) || 'hotel_reviews');
const { getReviews } = useApi();
const { data } = await useAsyncData('text-videos', () => getReviews({ table: table.value, limit: 12 }), { watch: [table, resolution] });
if (!VALID_RESOLUTIONS.includes(resolution.value)) { throw createError({ statusCode: 404 }); }
</script>

<template>
  <div>
    <div class="flex items-center justify-between mb-6 flex-wrap gap-3">
      <h1 class="text-2xl font-bold">Videos <span class="text-blue-600">{{ resolution }}</span></h1>
      <div class="flex gap-2 flex-wrap text-sm">
        <NuxtLink v-for="r in VIDEO_RESOLUTIONS" :key="r" :to="`/text-videos/${r}?table=${table}`"
          :class="resolution === r ? 'px-3 py-1 rounded-full border bg-blue-600 text-white border-blue-600' : 'px-3 py-1 rounded-full border border-gray-300 hover:bg-gray-50'">{{ r }}</NuxtLink>
      </div>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <ReviewCardWithVideo v-for="r in data?.data" :key="r.id" :review="r" :resolution="resolution" />
    </div>
  </div>
</template>
