// frameworks/angular-v19.1/src/app/pages/list/list.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { ReviewCardComponent } from '../../components/review-card/review-card.component';
import { Review } from '../../config';

@Component({
  selector: 'app-list',
  standalone: true,
  imports: [ReviewCardComponent],
  template: `
    <h1 class="text-2xl font-bold mb-6">Review List <span class="text-sm font-normal text-gray-400">(JMeter target – 100 items)</span></h1>
    <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
      @for (r of reviews; track r.id) {
        <app-review-card [review]="r" />
      }
    </div>
  `,
})
export class ListComponent implements OnInit {
  reviews: Review[] = [];

  constructor(private api: ApiService, private route: ActivatedRoute) {}

  ngOnInit() {
    const table = this.route.snapshot.queryParamMap.get('table') ?? 'hotel_reviews';
    const delay = Number(this.route.snapshot.queryParamMap.get('delay') ?? 0);
    this.api.getReviews({ table, limit: 100, delay }).subscribe(res => { this.reviews = res.data; });
  }
}

// frameworks/nextjs-v14.2.3/app/list/page.tsx
import { API_BASE } from '@/lib/config';
import { ReviewCard } from '../components/ReviewCard';

export default async function ListPage({
  searchParams,
}: {
  searchParams: { table?: string; delay?: string };
}) {
  const table = searchParams.table ?? 'hotel_reviews';
  const delay = searchParams.delay ?? '0';

  const res = await fetch(
    `${API_BASE}/api/reviews?table=${table}&limit=100&delay=${delay}`,
    { cache: 'no-store' }
  );
  const { data: reviews } = await res.json();

  return (
    <div>
      <h1 className="text-2xl font-bold mb-6">
        Review List{' '}
        <span className="text-sm text-gray-400 font-normal">(100 items – JMeter target)</span>
      </h1>
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
        {reviews.map((r: any) => <ReviewCard key={r.id} review={r} />)}
      </div>
    </div>
  );
}
